# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main-sp2-admin" ]
env:
  MAIN_DIR: admin.figmaps.com
  SUB_DIR: sp2-admin

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Copy env file
        run: cp /var/www/$MAIN_DIR/env.production.ts /var/www/$MAIN_DIR/_work/$SUB_DIR/$SUB_DIR/src/env.ts
      - run: npm i
      - run: npm run build
      - name: Remove old deployment
        continue-on-error: true
        run: '[ -d "/var/www/$MAIN_DIR/build-old" ] && rm -rf /var/www/$MAIN_DIR/build-old'
      - name: Archive current deployment
        continue-on-error: true
        run: '[ -d "/var/www/$MAIN_DIR/build" ] && mv /var/www/$MAIN_DIR/build /var/www/$MAIN_DIR/build-old'
      - name: Apply new deployment
        continue-on-error: true
        run: cp -r /var/www/$MAIN_DIR/_work/$SUB_DIR/$SUB_DIR/dist /var/www/$MAIN_DIR/build
      - name: Set permissions
        continue-on-error: true
        run: chmod -R 777 /var/www/$MAIN_DIR/build

